dofile "Mechanics/Pizzaface"
dofile "Mechanics/Snick"
dofile "Mechanics/Combo Bar"
dofile "Mechanics/Escape Spawner"
dofile "Mechanics/PVP"
dofile "Mechanics/Secrets"
dofile "Mechanics/Treasures"
dofile "Mechanics/Toppins/Main"
dofile "Mechanics/Ranks"
dofile "Mechanics/Exit Signs"
dofile "Mechanics/Lap Portal"